# Generated by Django 3.2.15 on 2023-04-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Геог. широта')),
                ('lon', models.FloatField(verbose_name='Геог. долгота')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес места')),
                ('data', models.DateField(verbose_name='Дата запроса к геокодеру')),
            ],
        ),
    ]
