# Generated by Django 3.2.15 on 2023-03-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_order_elements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_elements',
            new_name='OrderElements',
        ),
    ]
