# Generated by Django 3.2.15 on 2023-04-02 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_rename_order_elements_orderelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelements',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
