# Generated by Django 3.2.15 on 2023-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Ресторан', 'Ресторан'), ('Курьер', 'Курьер'), ('Доставлен', 'Доставлен')], default='Менеджер', max_length=100, verbose_name='Статус'),
        ),
    ]
