# Generated by Django 3.2.15 on 2023-04-12 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20230412_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelements',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
