# Generated by Django 3.2.15 on 2023-05-08 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_orderelements_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelements',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
